# Generated by Django 4.1.6 on 2023-02-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='My home town', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='notify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tag_id',
            field=models.CharField(default='TAG0001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
