# Generated by Django 4.1.6 on 2023-02-11 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_address_user_notify_user_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notify',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tag_id',
        ),
    ]
