version: '3.8'

services:
  django_rfid:
    build: .
    container_name: django_rfid
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
      - static_volume:/usr/src/app/static  # <-- bind the static volume
      - media_volume:/usr/src/app/media  # <-- bind the media volume
    ports:
      - "8000:8000"

    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER="redis://redis:6379/0"
      - CELERY_BACKEND="redis://redis:6379/0"
    depends_on:
      - redis
      - progressdb

  celery:
    build: .
    restart: always
    command: celery -A core worker  -l INFO 
    volumes:
      - .:/usr/src/app

    depends_on: 
      - django_rfid
      - redis

  redis:
    image: redis:7-alpine
    restart: always

  progressdb:
    image: postgres:15-alpine
    container_name: progressdb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data/

volumes:
  static_volume:  # <-- declare the static volume
  media_volume:  # <-- declare the media volume
  pgdata: