# Generated by Django 4.1.7 on 2023-02-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_rename_parent_guardian_member_parent_guardian_name_and_more'),
        ('api', '0002_rename_time_apidata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apidata',
            name='tag_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
