# Generated by Django 4.1.6 on 2023-02-12 14:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=20, verbose_name='First name')),
                ('lastname', models.CharField(max_length=20, verbose_name='Last name')),
                ('email', models.CharField(max_length=255, unique=True, verbose_name='Email Address')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, verbose_name='Phone number')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='Address')),
                ('parent_guardian', models.CharField(max_length=200, unique=True, verbose_name='Parent or Guardian name')),
                ('tag_id', models.CharField(max_length=20, unique=True, verbose_name='Tag ID')),
                ('notify', models.BooleanField(default=False, verbose_name='Notification')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
