# Generated by Django 4.1.5 on 2023-02-24 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="device",
            old_name="decription",
            new_name="description",
        ),
    ]
