name: Example workflow using Snyk
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: docker.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: rfid

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10.6"
        cache: 'pip' # Caching pip dependencies

    - run: pip install -r requirements.txt


    - name: Login To Dockerhub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: o3cloudng/rfid:latest

    - name: Install pipenv
      run: pip install pipenv
        
    - uses: actions/checkout@master
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      env:
        SNYK_TOKEN: ${{secrets.SNYK_TOKEN}}

        
    # - name: Set up Node 14
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 14
    # - name: install Snyk CLI
    #   run: npm install -g snyk
    # - name: run Snyk Open Source Test
    #   run: snyk test
    # - name: run Snyk Code Test
    #   run: snyk code test
        